# 数学

## 线代

In [1]:
import sys
import numpy as np

print('Python:{}'.format(sys.version))
print('Numpy:{}'.format(np.__version__))

Python:3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Numpy:1.16.5


In [2]:
# scalar
x = 6
x

6

In [4]:
# vector
x = np.array((1, 2, 3))
x

array([1, 2, 3])

In [5]:
print('vector dimensions: {}'.format(x.shape))
print('vector size: {}'.format(x.size))

vector dimensions: (3,)
vector size: 3


In [6]:
# matrix
x = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
print('matrix dimensions: {}'.format(x.shape))
print('matrix size: {}'.format(x.size))

matrix dimensions: (3, 3)
matrix size: 9


In [8]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# tensor
x = np.ones((3, 3, 3))

In [10]:
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
# indexing
A = np.ones((5, 5), dtype=np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
A[0,1]=2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
A[:,0]=3
A

array([[3, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 1, 1, 1, 1]])

In [14]:
A[:,:]=5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
A= np.ones((5, 5, 5), dtype=np.int)
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [16]:
# matrix operation
A= np.matrix([[1, 2], [3, 4]])
B = np.ones((2, 2), dtype=np.int)

In [17]:
A

matrix([[1, 2],
        [3, 4]])

In [18]:
B

array([[1, 1],
       [1, 1]])

In [19]:
C = A*B
C

matrix([[3, 3],
        [7, 7]])

In [20]:
# matrix transpose
A = np.array(range(9))
A = A.reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [22]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 特征值与特征向量 EigenValue & Eigenvector

In [23]:
A = np.arange(9) - 3
A

array([-3, -2, -1,  0,  1,  2,  3,  4,  5])

In [24]:
B = A.reshape((3, 3))
B

array([[-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [25]:
# Euclidean (L2) norm - default
print(np.linalg.norm(A))
print(np.linalg.norm(B))

8.306623862918075
8.306623862918075


In [26]:
# the Frogenius norm is the L2 norm for a matrix
print(np.linalg.norm(B, 'fro'))

8.306623862918075


In [28]:
# the max norm (P = infinity)
print(np.linalg.norm(A, np.inf))
print(np.linalg.norm(B, np.inf))

5.0
12.0


In [30]:
# vector normalization - normalization to produce a unit vector
norm = np.linalg.norm(A)
A_unit = A / norm
print(A_unit)

[-0.36115756 -0.24077171 -0.12038585  0.          0.12038585  0.24077171
  0.36115756  0.48154341  0.60192927]


In [31]:
# the manitude of a unit vector is equal to 1
np.linalg.norm(A_unit)

0.9999999999999999

In [32]:
# find the eienvalues and eigenvectors for a simple square matrix
A = np.diag(np.arange(1, 4))
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [34]:
eigenvalues

array([1., 2., 3.])

In [35]:
eigenvectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# the eigenvalue w[i] corresponds to the eigenvector v[:,i]
print('eigenvalue:', eigenvalues[1])
print('eigenvector:', eigenvectors[:, 1])

eigenvalue: 2.0
eigenvector: [0. 1. 0.]


In [38]:
np.linalg.inv(eigenvectors)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# verify eigendecomposition
matrix = np.matmul(np.diag(eigenvalues), np.linalg.inv(eigenvectors))
output = np.matmul(eigenvectors, matrix).astype(np.int)
output

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])